### PR TITLE
Create Chechen-Arabic.tsv

### PR DESCRIPTION
**Pull request by Plkmoi**

### CODE REVIEW

**Comment by danielinux7** [comment]
Hello,
Is there a reason why you are submitting the same content with different file formats (xlsx, txt, csv and tsv)?

**Comment by Plkmoi** [comment]
I thought more formats would be better as there would be a range of options.

**Comment by danielinux7** [comment]
I want to reduce the footprint of the repository, we are using public resources provided for free by Github, the least we can do is to remove redundancy in order to save cost and time on servers, there save energy.

**Comment by Plkmoi** [comment]
I made modifications to Pull Request.

**Comment by danielinux7** [comment]
Ok 👍

**Pull request merged**
